### PR TITLE
Added game music when the game starts

### PR DESCRIPTION
**Pull request by gundeep77**
A game music will be played when anyone enters the game by clicking done.

### CODE REVIEW

**Comment by FinnKr** [comment]
Sounds good. Where did you get that music from?

**Comment by gundeep77** [comment]
> Sounds good. Where did you get that music from?

This music is actually from the game pocket tanks, i just downloaded it from google. Thought this would improve the playing experience. So....

**Comment by FinnKr** [comment]
Do you know the license of this "song"? So I know if I can actually use it or not.

**Comment by gundeep77** [comment]
> Do you know the license of this "song"? So I know if I can actually use it or not.

I am sorry, I don't know about the license, I just used to play in my childhood and was fond of it, it just came to mind, so I used it.

**Comment by FinnKr** [comment]
Okay I'll go and ask for permissions.

**Pull request merged**
